### ISSUE TITLE
Make sure linkchecker only has read permissions

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.linkchecker#27] opened 2019-01-11 08:21 UTC
It is important that the linkchecker only has read permissions. Otherwise he might delete content.

**Comment by maethu** [comment] 2019-02-13 15:38
Mit transaction.doom() kann sichergestellt werden, dass keine Veränderungen an der DB commited werden.

**Comment by maethu** [comment] 2019-02-13 15:44
Since the script run it's own instance, All possible changes are not committed anyway.
So this issues has been resolved by design of the software 👍

**Closed as completed by maethu** 2019-02-13 15:44 UTC
